---
title: "R Notebook"
output: html_notebook
---


## Time Series Analysis in R
```{r}
library(astsa)
```

```{r}
# Johnson and Johnson Earnings
plot(jj, type="o", ylab="Quarterly Earnings per Share")
```

```{r}
# Global Warming
plot(globtemp, type="o", ylab="Global Temperature Deviations")
```

```{r}
# Speech Data
plot(speech, type="l")
```

```{r}
# Dow Jones Returns
library(xts)
djiar = diff(log(djia$Close))[-1] # approximate returns
plot(djiar, main="DJIA Returns", type="n")
lines(djiar)
```

```{r}
# fMRI Imaging
par(mfrow=c(2,1))
ts.plot(fmri1[,2:5], col=1:4, ylab="BOLD", main="Cortex")
ts.plot(fmri1[,6:9], col=1:4, ylab="BOLD", main="Thalamus & Cerebellum")
```

```{r}
# White Noise vs. Moving Average
w = rnorm(500,0,1) # 500 N(0,1) variates
v = filter(w, sides=2, filter=rep(1/3,3)) # moving average
par(mfrow=c(2,1))
plot.ts(w, main="white noise")
plot.ts(v, ylim=c(-3,3), main="moving average")

```


```{r}
# Auto Regression
w = rnorm(550,0,1) # 50 extra to avoid startup problems
x = filter(w, filter=c(1,-.9), method="recursive")[-(1:50)] # remove first 50
plot.ts(x, main="autoregression")

```


